### ISSUE TITLE
Docker Compose build Failure

### ISSUE THREAD

**Issue by timjohn009** [mbay-SAG/cumulocity-thinedge-example#2]
Although i did follow the checkout process for all the images as mentioned in the Readme file,
but for some reason the the setup is looking for 'ApamaServerLicense.xml' and which is why the setup is failing.
It would be really helpful if you could provide me some insight on how to resolve this.

> Step 29/30 : COPY --chown=admin:admin ApamaServerLicense.xml ${APAMA_WORK}/license/ApamaServerLicense.xml
ERROR: Service 'apama' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder008358929/ApamaServerLicense.xml: no such file or directory

**Comment by timjohn009** [comment]
Issue resolved.

**Comment by mbay-SAG** [comment]
The licence for Apama is currently needed. Added that part into the documentation. Thanks for the hint.
